# Generated by Django 6.0.2 on 2026-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_diag',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_med',
            field=models.TextField(blank=True),
        ),
    ]
