# Generated by Django 6.0.5 on 2026-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_fixed_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_schedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fixed_schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
