# Generated by Django 6.0.5 on 2026-05-13 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_fixed_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_schedule',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
