# Generated by Django 6.0.5 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_fixed_schedule_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixed_schedule',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='fixed_schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
