# Generated by Django 6.0.2 on 2026-05-12 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='장학금 이름')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('benefit', models.TextField(verbose_name='혜택')),
                ('provider', models.CharField(max_length=100, verbose_name='제공주체')),
                ('deadline', models.DateTimeField(verbose_name='마감일')),
                ('min_grade', models.FloatField(verbose_name='최소 학점')),
                ('description', models.TextField(verbose_name='상세 설명')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tuition', models.IntegerField(verbose_name='등록금')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='이름')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('income_range', models.IntegerField(verbose_name='소득분위')),
                ('major_id', models.IntegerField(verbose_name='전공번호')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.school', verbose_name='학교번호')),
            ],
        ),
        migrations.CreateModel(
            name='UserScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='상태')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='저장시간')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.user')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_range', models.IntegerField(verbose_name='소득분위')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.scholarship')),
            ],
            options={
                'unique_together': {('income_range', 'scholarship')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.IntegerField(verbose_name='전공번호')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.scholarship')),
            ],
            options={
                'unique_together': {('major_id', 'scholarship')},
            },
        ),
    ]
