# Generated by Django 4.2.30 on 2026-05-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0005_crewgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', '기부 예정'), ('completed', '기부 완료')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='crew.crew')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='crew.crewgoal')),
            ],
        ),
    ]
