# Generated by Django 4.2 on 2026-05-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '가수',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_key', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('lowest_pitch', models.CharField(max_length=10)),
                ('highest_pitch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '노래',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('lowest_pitch', models.CharField(max_length=10)),
                ('highest_pitch', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '회원',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
            ],
            options={
                'db_table': '플레이리스트',
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.song')),
            ],
            options={
                'db_table': '노래+가수',
                'unique_together': {('song', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.song')),
            ],
            options={
                'db_table': '플레이리스트+노래',
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
