# Generated by Django 6.0.2 on 2026-05-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('DM', 'Direct message'), ('GROUP', 'Group chat')], default='DM', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chat_languages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_language_code', models.ForeignKey(db_column='preferred_language_code', on_delete=django.db.models.deletion.PROTECT, related_name='preferred_users', to='chat.language')),
            ],
            options={
                'verbose_name': 'chat user',
                'verbose_name_plural': 'chat users',
                'db_table': 'chat_users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File')], default='TEXT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(db_column='chat_room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('original_language_code', models.ForeignKey(db_column='original_language_code', on_delete=django.db.models.deletion.PROTECT, related_name='original_messages', to='chat.language')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chat.user')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_chat_rooms', to='chat.user'),
        ),
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_content', models.TextField()),
                ('translation_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat.message')),
                ('target_language_code', models.ForeignKey(db_column='target_language_code', on_delete=django.db.models.deletion.PROTECT, related_name='message_translations', to='chat.language')),
            ],
            options={
                'db_table': 'chat_message_translations',
                'constraints': [models.UniqueConstraint(fields=('message', 'target_language_code'), name='unique_message_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(db_column='chat_room_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatroom')),
                ('display_language_code', models.ForeignKey(db_column='display_language_code', on_delete=django.db.models.deletion.PROTECT, related_name='chat_room_members', to='chat.language')),
                ('last_read_message', models.ForeignKey(blank=True, db_column='last_read_message_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to='chat.user')),
            ],
            options={
                'db_table': 'chat_room_members',
                'constraints': [models.UniqueConstraint(fields=('chat_room', 'user'), name='unique_chat_room_member')],
            },
        ),
    ]
