# Generated by Django 6.0.2 on 2026-05-04 14:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_hash', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 17, 809051, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(verbose_name=128)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 17, 809532, tzinfo=datetime.timezone.utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
