# Generated by Django 6.0.2 on 2026-05-04 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 18, 135675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 18, 134937, tzinfo=datetime.timezone.utc)),
        ),
    ]
