# Generated by Django 6.0.2 on 2026-05-04 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_interest_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 27, 716300, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 14, 51, 27, 715801, tzinfo=datetime.timezone.utc)),
        ),
    ]
