# Generated by Django 6.0.2 on 2026-05-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('MName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LName', models.CharField(max_length=100)),
                ('CourseLevel', models.IntegerField(default=0)),
                ('Category', models.CharField(default='교양', max_length=50)),
                ('major_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='major.major')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisiteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='major.lecture')),
                ('pre_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='major.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Level', models.IntegerField(default=0)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_users', to='major.major')),
                ('major_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majored_users', to='major.major')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.lecture')),
                ('major_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.user')),
            ],
        ),
    ]
