# Generated by Django 4.2.30 on 2026-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crew_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
