# Generated by Django 4.2.30 on 2026-05-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_crew_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('target_distance', models.FloatField()),
                ('donation_amount', models.PositiveBigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='crew.crew')),
            ],
        ),
    ]
