# Generated by Django 6.0.2 on 2026-05-14 04:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('hash', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('publisher', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 14, 4, 22, 14, 199585, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('crawl_interval_minutes', models.PositiveIntegerField()),
                ('crawled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 14, 4, 22, 14, 199187, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='InboxNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('matched_keywords', models.TextField()),
                ('reason', models.TextField()),
                ('is_read', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.source'),
        ),
        migrations.CreateModel(
            name='SourceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.source')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
