# Generated by Django 6.0.2 on 2026-05-04 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 51, 27, 717213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 4, 14, 51, 27, 716902, tzinfo=datetime.timezone.utc)),
        ),
    ]
