# Generated by Django 6.0.2 on 2026-05-14 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 7, 4, 14, 524618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 7, 4, 14, 524363, tzinfo=datetime.timezone.utc)),
        ),
    ]
