# Generated by Django 6.0.2 on 2026-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='crawl_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
