# Generated by Django 4.2.30 on 2026-05-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crew', '0004_crew_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(choices=[('running', '러닝'), ('walking', '걷기'), ('cycling', '자전거'), ('swimming', '수영'), ('hiking', '등산'), ('etc', '기타')], max_length=20)),
                ('distance', models.FloatField()),
                ('duration', models.PositiveIntegerField()),
                ('record_date', models.DateField()),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_records', to='crew.crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
