# Generated by Django 6.0.5 on 2026-05-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('estimated_duration', models.IntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('WO', 'Working'), ('DO', 'Done')], default='PE', max_length=2)),
            ],
        ),
    ]
