# Generated by Django 6.0.5 on 2026-05-13 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_scheduled_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_history',
            name='task_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
