# Generated by Django 6.0.5 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_history_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_task',
            name='scheduled_id',
        ),
        migrations.RemoveField(
            model_name='task_history',
            name='history_id',
        ),
        migrations.AddField(
            model_name='scheduled_task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='task_history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
