# Generated by Django 6.0.2 on 2026-05-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatchaItemList',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'gatcha_item_list',
            },
        ),
        migrations.CreateModel(
            name='GatchaType',
            fields=[
                ('gatcha_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'gatcha_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('currency_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='GatchaPoolItem',
            fields=[
                ('pool_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drop_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.gatchaitemlist')),
                ('gatcha', models.ForeignKey(db_column='gatcha_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.gatchatype')),
            ],
            options={
                'db_table': 'gatcha_pool_item',
            },
        ),
        migrations.CreateModel(
            name='UserGatchaRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gatcha', models.ForeignKey(db_column='gatcha_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.gatchatype')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.gatchaitemlist')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.user')),
            ],
            options={
                'db_table': 'user_gatcha_record',
            },
        ),
        migrations.CreateModel(
            name='UserItemList',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.gatchaitemlist')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='gatcha.user')),
            ],
            options={
                'db_table': 'user_item_list',
            },
        ),
    ]
