# Generated by Django 6.0.2 on 2026-05-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_remove_diagnosisreport_user_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreport',
            name='symptom_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnosis.symptomreport'),
        ),
    ]
