# Generated by Django 6.0.2 on 2026-05-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlog',
            old_name='tutoring_class',
            new_name='class_info',
        ),
    ]
